### ISSUE TITLE
SeminarioII_revEdécio

### ISSUE THREAD

**Issue by edeciofernando** [gTheil/Hollow#10]
Ok. Mudanças na arte ficaram muito boas. Parabéns.

Sugestões:
- [x] Adicionar dicas para auxiliar os jogadores sobre o funcionamento do jogo.
- [x] Cuidado com o cronograma, sistema grande.

**Comment by gTheil** [comment]
> Adicionar dicas para auxiliar os jogadores sobre o funcionamento do jogo.

Como discutido no último seminário de andamento, haverá uma tela explicando os controles básicos do jogo; porém, quanto às mecânicas particulares do jogo, o gênero Metroidvania presa por ensinar o jogador à medida que ele joga, portanto não foi pensado um tutorial ou uma área de dicas. Talvez para trabalhos futuros.

> Cuidado com o cronograma, sistema grande.

Felizmente, o sistema encontra-se praticamente concluído: o mapa está quase pronto, a arte está finalizada e foram implementados sistemas para lidar com a sonorização do jogo.

**Comment by gTheil** [comment]
> Adicionar dicas para auxiliar os jogadores sobre o funcionamento do jogo.

Como discutido no último seminário de andamento, haverá uma tela explicando os controles básicos do jogo; porém, quanto às mecânicas particulares do jogo, o gênero Metroidvania presa por ensinar o jogador à medida que ele joga, portanto não foi pensado um tutorial ou uma área de dicas. Talvez para trabalhos futuros.

> Cuidado com o cronograma, sistema grande.

Felizmente, o sistema encontra-se praticamente concluído: o mapa está quase pronto, a arte está finalizada e foram implementados sistemas para lidar com a sonorização do jogo.
