### ISSUE TITLE
BancaFinal - revLuzzardi

### ISSUE THREAD

**Issue by pluzzardi** [gTheil/Hollow#5]
1.  Melhorar a Motivação e Justificativa (como na apresentação)

2. Falar um pouco mais lento

3. Porque personagem não morreu com vida zero?

4. Personagem não está muito grande?

**Comment by gTheil** [comment]
> Melhorar a Motivação e Justificativa (como na apresentação)

Feito.

> Falar um pouco mais lento

Entendido.

> Porque personagem não morreu com vida zero?

Discutido durante a banca anterior.

> Personagem não está muito grande?

Os gráficos utilizados atualmente são, por enquanto, apenas placeholders. Eles devem ser trocados no futuro. Por enquanto o personagem está deste tamanho para manter proporção com os inimigos e com o cenário.
