### ISSUE TITLE
BancaFinalTCCI - revEdécio

### ISSUE THREAD

**Issue by edeciofernando** [gTheil/Hollow#6]
Comentários / sugestões:
- [x] Muito boa a apresentação e desenvolvimento das tarefas para o TCC I
- [x] Pensar em formas / citar no artigo aspectos de comercialização do jogo
- [x] Descrever sobre as tecnologias utilizadas
- [x] Consultar / citar no artigo sobre Inteligência Artificial (relacionado ao aspecto de aprendizado do personagem)

**Comment by gTheil** [comment]
>  Muito boa a apresentação e desenvolvimento das tarefas para o TCC I

Obrigado!

>  Pensar em formas / citar no artigo aspectos de comercialização do jogo

No momento não há foco na comercialização do jogo, mas será pesquisado para o futuro. Além disso, foi discutido na banca anterior opções de comercialização.

> Descrever sobre as tecnologias utilizadas

Feito.

> Consultar / citar no artigo sobre Inteligência Artificial (relacionado ao aspecto de aprendizado do personagem)

Uma pesquisa será realizada e incluída no artigo.
