### ISSUE TITLE
SeminarioI_revEdecio

### ISSUE THREAD

**Issue by edeciofernando** [gTheil/Hollow#8]
Muito bom. Apresentação e descrição do software.
Sugestão:
- [x] Como são apenas 2 tecnologias utilizadas, descrever mais sobre elas.

**Comment by gTheil** [comment]
> Como são apenas 2 tecnologias utilizadas, descrever mais sobre elas.

As descrições das tecnologias foram expandidas. Sobre a tecnologia Unity foi descrito um pouco sobre sua história, suas funcionalidades e plataformas suportadas. Quanto a linguagem C#, foi descrito um pouco de sua história, assim como alguns de seus objetivos e características.
